### ISSUE TITLE
The use of this library for survey's with dynamic sections?

### ISSUE THREAD

**Issue by swcurran** [Pierre-Sassoulas/django-survey#1]
We have a need for an app that contains a survey, but the requirements of the survey are such that the sections of the survey are repeated multiple times.  For example:

Q: How many people are involved?  <Number> (Answer: 2)

For person 1:

- Q: What is there name?
- Q: What is there age?

For person 2:

- Q: What is there name?
- Q: What is there age?

There would also need to be a way to access the data for reporting - or at least for passing it to a template for presentation.

Assuming the existing library does not contain this functionality, what do you think the complexity of adding such a capability would be?  Unreasonable?  Easy?  Somewhere in between?

Thanks!

**Comment by Pierre-Sassoulas** [comment]
I don't think I understood your example really well.

Do you want to have the same questions multiple time ? If so then you can copy paste the question and the possibles answer choices in another question. I could create defined answers that you can choose from, in 1 to 4 hours but it has always been easier to just copy paste the possibles answers and it would possibly make the creation of question more complicated.

Do you want to ask the same questions to multiple persons ? If so you can ask the user to log in before doing the survey and everyone will have his or her own response(s) saved. Even without logging, each person would be a different anonymous user.

Don't hesitate to be more precise in what you want to achieve if I did not understand that part.

Then, regarding the access to data in the survey, you can look at it in the django admin directly or export it in csv, tex and pdf (anonymised). More details in the Readme.md. The data are stored in models, so its possible to create a layer of presentation with django template (D3.js would be a good candidate) or by creating another child class of Survey2X (Survey2Xlsx ?). There are already a lot of helper function in survey.model so the implementation time would depend on your mastery of the presentation layer or the format you want to export too.

I hope this help.

**Comment by swcurran** [comment]
Thanks for the response!  The key feature we are looking for is a section of questions that are repeated based on the answer to a previous numerical question.  So in my example, the question:

Q: How many people are involved?

The answer could be 1, 10, 1000, and the following two questions (an arbitrary section of questions) would be asked 1, 10 or 1000 times based on the answer.

Basically, we would have an array of responses for the section, and be able to access the questions for reporting by iterating through the unknown count of response sets.

The specific use case is not using this as a general population survey engine, but more as a form to be completed by the users of the system.  We are looking for a good data-entry form engine that includes that capability and thought this module might be a fit.

I hope that helps.

**Comment by Pierre-Sassoulas** [comment]
> The specific use case is not using this as a general population survey engine, but more as a form to be completed by the users of the system. We are looking for a good data-entry form engine

Would'nt it be more convenient to use google sheets, excel, or similar, like this ?
![sheets](https://user-images.githubusercontent.com/5493666/33020511-f447f36a-cdfe-11e7-8571-7190b3da07f6.png)

**Comment by swcurran** [comment]
No, google forms/docs won't work.  We're building an web app (specifically for a Government Service to Citizens), and Google Forms does not support the feature I've described.
