### ISSUE TITLE
Rearranged components 

### ISSUE THREAD

**Issue by gpxlqa** [Pierre-Sassoulas/django-survey#101]
The "card" to create questions occupies all horizontal pages and the fields should be rearranged in order to occupy less space. In other words, develop this section available vertically, not horizontally.

![unnamed](https://user-images.githubusercontent.com/6579591/95638149-0b759b00-0a6a-11eb-970a-2da1e01b94f9.png)

**Comment by Pierre-Sassoulas** [comment]
Done by @capaci in #102

**Comment by a-wip0** [comment]
why don't just resize the "card" instead of making it vertical, now user have to scroll far just to create the few question

**Comment by Pierre-Sassoulas** [comment]
@a-wip0 I'm open to suggestion, if you have a better idea I would merge it for sure. By the way this change is not released yet.
