### ISSUE TITLE
What does template mean in the Add Survey page and how to use it

### ISSUE THREAD

**Issue by a-wip0** [Pierre-Sassoulas/django-survey#104]
![image](https://user-images.githubusercontent.com/33978908/96415079-35704f80-1218-11eb-9172-19c43bb409a5.png)

What should i type there if i want to use template?
How to use it?
where it get implemented?

**Comment by Pierre-Sassoulas** [comment]
Hello, by default the template used is `survey/one_page_survey.html` is the survey is displayed all in one page or `survey/survey.html` if not. You can use another template by changing the value for something else (probably a template you created yourself specifically for your survey), the file must exists and be accessible by django at runtime.

**Comment by Pierre-Sassoulas** [comment]
The implementation is mostly here: https://github.com/Pierre-Sassoulas/django-survey/blob/60318c2080fbf9e834b8dcafa83132901b43a369/survey/views/survey_detail.py#L64

**Comment by a-wip0** [comment]
thank you for your response, i have another
1. does the sort by question and by category work? i tried it and it didn't work
2. about the image question, how to put the asnwer option? url? local image?

**Comment by Pierre-Sassoulas** [comment]
I never used images, both url and local images are good idea. It's probably only a template link in static though. You can open a new issue for the sorting bug, or for the images by url/local image, I would welcome a pull request for both this :)
