### ISSUE TITLE
Multiple choice checkbox displays on one line

### ISSUE THREAD

**Issue by d-horner** [Pierre-Sassoulas/django-survey#108]
Using a large list of multiple select options incorrectly displays choices on one line:
![image](https://user-images.githubusercontent.com/29963998/98780621-5d0c9f00-23f5-11eb-9f73-f20dc8854a2f.png)

Adding a `<br>` tag within the for loop in the [questions.html template](https://github.com/Pierre-Sassoulas/django-survey/blob/ee3c3518beef09d0eb412dfc1da9829c8e888e63/survey/templates/survey/question.html#L24-L27) resolves this display issue:
![image](https://user-images.githubusercontent.com/29963998/98780943-e8863000-23f5-11eb-83d6-743873b364e9.png)

I am guessing it is due to wrapping and some CSS somewhere, but I've not had the chance to look into it quite yet.

**Comment by Pierre-Sassoulas** [comment]
Good catch ! Could we use something like this instead ? https://getbootstrap.com/docs/4.0/components/input-group/#checkboxes-and-radios. Or maybe django boostrap form "crispy" `{{ form|crispy }}`. I'll let you choose the solution between those 2 or a simple `<br>` as we already have boostrap and django-boostrap-form as dependencies.

**Comment by d-horner** [comment]
I was actually going to suggest creating a boostrap4 branch as the current repo makes use of bootstrap3 (I did a quick once over and there were only one or two CSS selectors that should/would need updating).

I would propose going a step further and creating a more accessible stylesheet than the current implementation. The grey backdrop doesn't meet the contrast ratio required for [WCAG 3](https://www.w3.org/WAI/standards-guidelines/wcag/wcag3-intro/) accessibility guidelines - I know this is a minor suggestion, possibly due to use case (patient research)/HIPAA compliance background, but it can't hurt?

If this is something that you would be interested in pursuing I would happily contribute to this end!

**Comment by Pierre-Sassoulas** [comment]
Sure thing, let's do this in another pull request than polish translation, so I can merge polish and <br> first then ;)

I created https://github.com/Pierre-Sassoulas/django-survey/issues/109.
