### ISSUE TITLE
Select tag not displayed properly

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [Pierre-Sassoulas/django-survey#11]
Fix could be in survey/templates/survey/question.html displaying form directly instead of itering on field.

It's also possible to use bootstrap-form directly to render form.

**Comment by Pierre-Sassoulas** [comment]
@nsuzue this app render form really well for most case : https://github.com/tzangms/django-bootstrap-form

**Comment by 1000camels** [comment]
I am using the version installed via pip and my select fields are not rendering correctly. Specifically, the <select> elements are not in the markup. Is this the same bug?

**Comment by Pierre-Sassoulas** [comment]
It seems like it. If you want to fix this, feel free to make a pull request. It should be simple with `django-bootstrap-form`.

**Comment by Pierre-Sassoulas** [comment]
@florianmouchantaf There might be the start of a fix in #47 but there are also regressions so I cannot merge it as it is.
