### ISSUE TITLE
Creating survey from outside the admin site

### ISSUE THREAD

**Issue by yahya-abou-imran** [Pierre-Sassoulas/django-survey#130]
Hello!
I would to permit certain types of users (not staff) with some kinds of permissions to access a page where they can create surveys.
I think a section in the doc could be added to explain how to achieve that with the minimal amount of effort.
I was about to re-implement several views and forms, but I think there should be a simpler way to retrieve the admin views…

**Comment by Pierre-Sassoulas** [comment]
Hello, I think this is doable by creating some custom right for users regarding Surveys. This is not specific to this app in fact:

> Access to view objects is limited to users with the « view » or « change » permission for that type of object.
> Access to view the « add » form and add an object is limited to users with the « add » permission for that type of object.

Source: https://docs.djangoproject.com/fr/2.2/topics/auth/default/
