### ISSUE TITLE
Select Image

### ISSUE THREAD

**Issue by tiagolagrecap** [Pierre-Sassoulas/django-survey#133]
Hi, im trying to use the option Select Image, but not working, i got this error.

'ImageSelectWidget' object has no attribute 'template_name'

Anyone can help me?
Thanks.

**Comment by Pierre-Sassoulas** [comment]
Duplicate of #115

**Comment by tiagolagrecap** [comment]
Closed, but still a not working.

tks.

**Comment by Pierre-Sassoulas** [comment]
You can still participate in the other issue, ask questions showing what you did, open a merge request fixing the problem, open a bounty on issue hunt so someone else fix the problem...  Opening a duplicate ticket with less content is not going to help.
