### ISSUE TITLE
Question without category is duplicated, if you have question with category in the same survey

### ISSUE THREAD

**Issue by a-wip0** [Pierre-Sassoulas/django-survey#134]
admin view

![image](https://user-images.githubusercontent.com/33978908/113512455-f26c2380-958e-11eb-8e13-072b2077b8a3.png)

survey view

![image](https://user-images.githubusercontent.com/33978908/113512475-044dc680-958f-11eb-9213-94d81d8cec20.png)

**Comment by Pierre-Sassoulas** [comment]
Thank you for reporting this issue !
