### ISSUE TITLE
Here a Dutch translation .po (nl) file

### ISSUE THREAD

**Issue by JohnGuyver117** [Pierre-Sassoulas/django-survey#143]
Hi,

Love your work, so I contribute a django.po file in Dutch. I'm not a developer so I hope someone can put the file in the right place.
I also had to rename the .po extension to .txt so I could attach the file to this message.

Have a nice day.

Kind regards, John

[django.txt](https://github.com/Pierre-Sassoulas/django-survey/files/6835041/django.txt)

**Comment by Pierre-Sassoulas** [comment]
Thank you for this, how do you want to be credited ? Is:

- [x] Dutch thanks to [John Guyver](https://github.com/JohnGuyver117)

Ok ?

**Comment by Pierre-Sassoulas** [comment]
Your translation is released in 1.3.35 :)

**Comment by JohnGuyver117** [comment]
Credited as John Guyver is fine.

Thanks Pierre.
