### ISSUE TITLE
How to display questions randomly ?

### ISSUE THREAD

**Issue by Aria-K-Alethia** [Pierre-Sassoulas/django-survey#169]
Hi,

Thank you for your code contribution!

I wonder if it is possible to display random questions for each subject.
That means I want to create a question pool with, say 10 questions, and for each subject, I want to select 5 questions randomly from the pool.

**Comment by Pierre-Sassoulas** [comment]
There's nothing to do that right now but I think it's possible to add this behaviour on top of the app.

**Comment by Aria-K-Alethia** [comment]
Thank you ! I wil try to customize the code.
