### ISSUE TITLE
String 'None' is displayed if category description is empty

### ISSUE THREAD

**Issue by maximloginov** [Pierre-Sassoulas/django-survey#176]
Value `category.description` is not checked against `None` in the template https://github.com/Pierre-Sassoulas/django-survey/blob/09a7c271c823dea598d177c2c4c4db03b7abc5f0/survey/templates/survey/survey.html#L36
It would be nicer to have something like `{{category.description|default_if_none:""}}` there

(I would make a PR request, but I cannot test is easily)

**Comment by Pierre-Sassoulas** [comment]
There's fixtures in the existing tests, you can add a null description and load the fixtures to check manually.
