### ISSUE TITLE
Enhancement: Static Folder structure

### ISSUE THREAD

**Issue by gnalbandian** [Pierre-Sassoulas/django-survey#19]
Hi, 
I believe it would  be a better practice to have the static folder reorganized adding a "survey" folder before the js, jss, and fonts folder.

- static
-- survey
---- js
---- css
---- fonts

In this way, we can do a python3 manage.py collectstatic and every app we have installed in our projectwill have its own static files without mixing them between.

**Comment by Pierre-Sassoulas** [comment]
Thank you for noticing and reporting that. I'm going to release 1.3.2 on pypi for python 3 in order to fix this problem and add spanish language.

**Comment by gnalbandian** [comment]
Great! Good to know.
