### ISSUE TITLE
Missing djangocms-rosetta in libs.

### ISSUE THREAD

**Issue by clercmedia** [Pierre-Sassoulas/django-survey#2]
I had this issue when trying to migrate the application.

ModuleNotFoundError: No module named 'rosetta.urls'

installed djangocms-rosetta :  pip install djangocms-rosetta fixed the issue.
Maybe it will be great to add it to your dependencies ? 

A+

**Comment by Pierre-Sassoulas** [comment]
Hello and thank you for the report, 

This is probably due to the default setting file that has rosetta in its installed apps. Rosetta should be a dev requirement only and should not be required to run survey.

How did you get the app (from pipy, by direct download, other...) ?, And what setting file are you using (default one, added survey in installed apps, other...) ? I'm asking in order to see if I need a warning in the default setting file, or if I need to redo the pypi package entirely :)

Regards,

**Comment by clercmedia** [comment]
Good questions , I toke it from the git repository and follow the install
procedure ?
Nothing modified so I should guess it's the default settings file ?


Christian Leclerc, CSSLP, OCMJEA, OCPJBCD, SCJP, ZCE
christian.leclerc@sphere3solutions.com

Sphere 3 Solutions inc.
No. d'entreprise: 842171969
2801, Boul. Des Promenades,C.P. 11016
Ste-Marthe-sur-le-Lac, Québec,J0N 1P0
Tél.: 514-940-1067
http://www.sphere3solutions.com

*CONFIDENTIALITÉ* L'information apparaissant dans ce message électronique
est de nature légalement privilégiée et confidentielle. Si ce message vous
est parvenu par erreur et que vous n'êtes pas le destinataire visé, vous
êtes par les présentes avisé que tout usage, copie ou distribution de ce
message est strictement interdit. Vous êtes donc prié de nous informer
immédiatement de cette erreur et de détruire ce message.

*CONFIDENTIALITY* The information in this message is legally privileged and
confidential. In the event of a transmission error and if you are not the
individual or entity mentioned above, you are hereby advised that any use,
copying or reproduction of this document is strictly forbidden. Please
advise us of this error and destroy this message.

**Comment by Pierre-Sassoulas** [comment]
Yes, you're probably using the default settings file. You can remove "rosetta" in installed_apps line 107. It is useful only for a developer that need to redo the translation.

I will try to make the documentation clearer for future user, and remove this one from master. 

Thanks again for reporting the problem.

**Comment by clercmedia** [comment]
No problem :)

Christian Leclerc, CSSLP, OCMJEA, OCPJBCD, SCJP, ZCE
christian.leclerc@sphere3solutions.com

Sphere 3 Solutions inc.
No. d'entreprise: 842171969
2801, Boul. Des Promenades,C.P. 11016
Ste-Marthe-sur-le-Lac, Québec,J0N 1P0
Tél.: 514-940-1067
http://www.sphere3solutions.com

*CONFIDENTIALITÉ* L'information apparaissant dans ce message électronique
est de nature légalement privilégiée et confidentielle. Si ce message vous
est parvenu par erreur et que vous n'êtes pas le destinataire visé, vous
êtes par les présentes avisé que tout usage, copie ou distribution de ce
message est strictement interdit. Vous êtes donc prié de nous informer
immédiatement de cette erreur et de détruire ce message.

*CONFIDENTIALITY* The information in this message is legally privileged and
confidential. In the event of a transmission error and if you are not the
individual or entity mentioned above, you are hereby advised that any use,
copying or reproduction of this document is strictly forbidden. Please
advise us of this error and destroy this message.

**Comment by clercmedia** [comment]
Hello Pierre, I have another issue, I can't make the survey to work ...
Every-time I answer a question, it keeps me on the same question over and
over again ?

Any clues ?


Christian Leclerc, CSSLP, OCMJEA, OCPJBCD, SCJP, ZCE
christian.leclerc@sphere3solutions.com

Sphere 3 Solutions inc.
No. d'entreprise: 842171969
2801, Boul. Des Promenades,C.P. 11016
Ste-Marthe-sur-le-Lac, Québec,J0N 1P0
Tél.: 514-940-1067
http://www.sphere3solutions.com

*CONFIDENTIALITÉ* L'information apparaissant dans ce message électronique
est de nature légalement privilégiée et confidentielle. Si ce message vous
est parvenu par erreur et que vous n'êtes pas le destinataire visé, vous
êtes par les présentes avisé que tout usage, copie ou distribution de ce
message est strictement interdit. Vous êtes donc prié de nous informer
immédiatement de cette erreur et de détruire ce message.

*CONFIDENTIALITY* The information in this message is legally privileged and
confidential. In the event of a transmission error and if you are not the
individual or entity mentioned above, you are hereby advised that any use,
copying or reproduction of this document is strictly forbidden. Please
advise us of this error and destroy this message.
