### ISSUE TITLE
Add an option to prevent user from modifying their response

### ISSUE THREAD

**Issue by Madhoumithaa-Veerasethu** [Pierre-Sassoulas/django-survey#34]
1. Can we restrict the number of responses that we get from a user?
According to my understanding, right now a user can edit and submit the form n number of times and the last response gets recorded. 
Instead is there a way to disable the survey in list.html page for a survey as soon as it is submitted?

2. Is there a provision to deactivate the survey after n number of days?

**Comment by Pierre-Sassoulas** [comment]
1. would be a new feature (addding it as an option for Survey). I will change the title of this issue to track this feature request.
2. would be possible manually if you unpublish the Survey but according to what someone said in #31 it's buggy right now. Doing so automatically after n days would be a new feature, could you open another issue if that is what you want ?

I welcome pull requests and I can answers your questions if you intend to make one :)

**Comment by Madhoumithaa-Veerasethu** [comment]
Okay. Thank you!

**Comment by giliam** [comment]
Hi @Pierre-Sassoulas , I would be interested in this feature and am ready to contribute. I just have a few questions:

1. Should I integrate in the `index_view` a query to the responses to differentiate polls that have already been answered from non answered polls? It would be nice to have "Take a survey" then "Edit your answer" or "Consult your answer".
2. As the `detail_view` will be different according to the editable or not option, do you recommend making a different template without forms or just to disable the form ?

Have a nice day!

**Comment by Pierre-Sassoulas** [comment]
Hey, thank you, that would be really appreciated.

Yes being able to have two options and a coherent user interface to match would be perfect!

I don't have a very clear memory about the way the code is done. If you have an editing view and a consulting view I think it's best to separate the two but you will probably be the best equipped to decide after seeing the state of the code.

I assigned the ticket to you, thanks again for proposing to do it :)

**Comment by giliam** [comment]
I have started looking at it but the SurveyDetail is kind of messy (imho): the response of the user is retrieved in the ResponseForm and not in the View. Looks like a wrong behaviour, isn't it? I can still find a way to implement current issue #34 but it will be a workaround...

**Comment by giliam** [comment]
Wow, it is even worse than I thought: the elements to multiple select are stored as a text block (kind of parsed list)? Hum. Looks like there is a huge amount of work here...

**Comment by Pierre-Sassoulas** [comment]
The way it is stored in the database could be modified or made better (handling retro-compatibility and the ability to do migrations, would be complicated if we do that), but I don't think it's required to prevent the user from modifying their response. It even makes it easier because you do not have multiple database objects to handle? Or did I miss something?

**Comment by giliam** [comment]
The problem is that I was just trying to make it possible to display your answers without modifying them but you must be right. I am going to ignore the things I don't understand and stay on my topic for now :D.

**Comment by giliam** [comment]
It remains there is probably a kind of security breach with all these safe tags used on templates and with the problem I mentioned earlier.

**Comment by Pierre-Sassoulas** [comment]
I agree with you. There was a lot of changes that I would have done if I kept on using the software  (especially if I had to use it externally with untrusted users). The fact that complicated migrations had to be done did not help either. Would you be willing to create another issue for this problem?

**Comment by giliam** [comment]
I will see :)
I don't understand, the tests on my branch (see https://github.com/giliam/django-survey/tree/patch-non-editable) are failing on Travis but not on my local computer. Any clue ? :S

**Comment by giliam** [comment]
Added on my patch-non-editable branch.
I will rebase to have a clean history.
