### ISSUE TITLE
Provision to disable the survey link after n number of days or make survey inactive?

### ISSUE THREAD

**Issue by Madhoumithaa-Veerasethu** [Pierre-Sassoulas/django-survey#35]
Is there a provision to deactivate the survey link after n number of days? Or make it inactive?
There is a option to make the users inactive in the admin portal. Is there a similar option for making it inactive?

**Comment by Pierre-Sassoulas** [comment]
Thanks you for creating a new issue, so we can distinguish this feature from the other one. As I said this is not possible yet but it would be doable by adding an option for the Survey.

**Comment by gjelsas** [comment]
#75 Maybe this is a way to this feature request?
