### ISSUE TITLE
Reusable App

### ISSUE THREAD

**Issue by rtucker-scs** [Pierre-Sassoulas/django-survey#4]
Is there anyway to use this as part of an existing django project?

**Comment by Pierre-Sassoulas** [comment]
Its the intended use. You can use pip install to add "django-survey-and-report" in your requirement, or copy the survey directory into your existing django project. Then just add "survey" to the app list in your existing project settings.

**Comment by rtucker-scs** [comment]
I dug deeper into the error I was getting. Not an issue with the app being reusable as much as the app isn't compatible with pluggable user model. I'll patch and send a PR
