### ISSUE TITLE
Displaying questions by category with a page for each category

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [Pierre-Sassoulas/django-survey#52]
Created by breaking down #3. 

We could create forms by category whatever the number of question inside them is.

Everything that should be changed for forms generation is in survey/forms.py.

**Comment by AntonOfTheWoods** [comment]
I am going to work on this. My idea is to turn `Survey.display_by_question` from a `Boolean` to an `Int` `Survey.display_method` with choices as follows:
```
    DISPLAY_METHOD_CHOICES = [
        (BY_QUESTION, 'By question'),
        (BY_CATEGORY, 'By category'),
        (BY_ALL, 'By all'),
    ]
```
How does that sound?

**Comment by Pierre-Sassoulas** [comment]
Thank you for working on this. I think this is the best way to do it. There will be a migration that can't be done automatically, (display_by_question=True becomes "by question" and False become "By all") but this seems inevitable.  I would name "By all" : "All in one page".

**Comment by AntonOfTheWoods** [comment]
For your comment https://github.com/Pierre-Sassoulas/django-survey/pull/91.

**Comment by Pierre-Sassoulas** [comment]
Done in #91, thanks to @AntonOfTheWoods
