### ISSUE TITLE
ModuleNotFoundError: No module named 'pysankey'

### ISSUE THREAD

**Issue by gjelsas** [Pierre-Sassoulas/django-survey#58]
when trying to export a result I got the message 
> ModuleNotFoundError: No module named 'pysankey' 

> 

I could fix it by changing a lowercase "s" to a uppercase "s"  in [survey/exporter/tex/question2tex_sankey.py](survey/exporter/tex/question2tex_sankey.py). 
Now it reads: `from pySankey import sankey` instead of `from pysankey import sankey`

**Comment by Pierre-Sassoulas** [comment]
Thank you for the report and for the fix :)

**Comment by Pierre-Sassoulas** [comment]
There seems to be a problem with the PySankey module, it works on Linux with one import and on windows with the other, I'll have to make it cross-platform compatible. I guess you're using Windows?

**Comment by gjelsas** [comment]
No, this happened in a Dockercontainer with the `FROM Python:3` Tag. But on LInux...

**Comment by Pierre-Sassoulas** [comment]
Thank you, I'll investigate then.

**Comment by Pierre-Sassoulas** [comment]
Closing because it must be a problem with the package installed locally.
