### ISSUE TITLE
Trying to create result in pdf format failed

### ISSUE THREAD

**Issue by gjelsas** [Pierre-Sassoulas/django-survey#60]
I try to generate a pdf result from a poll, but it stopps with: 
`sh: 1: xelatex: not found
sh: 1: xelatex: not found`

I think there is some path related issue here, but I keep looking at your code and don't see what I'm doing wrong.

It creates the .tex file, but aborts afterwards. I think the conversion tex to pdf is not working. 

Some more of the output is:
`survey.exporter.tex.latex_file.__init__() l.24 - Creating a document skeleton with document_class=article, document_option=12pt 
survey.exporter.tex.survey2tex.treat_question() l.40 - Treating, 1 Wiedereinladung erwuenscht? 
survey.exporter.tex.configuration.check_survey_exists() l.50 - Checking that 'TestDirigentin' is an existing survey. 
survey.exporter.tex.survey2tex.treat_question() l.40 - Treating, 2 Kandidat für Chefdirigent 
survey.exporter.tex.configuration.check_survey_exists() l.50 - Checking that 'TestDirigentin' is an existing survey. 
survey.exporter.survey2x.generate_file() l.92 - Wrote tex in /app/survey/tex/testdirigentin.tex 
sh: 1: xelatex: not found
sh: 1: xelatex: not found` 

Thank you for your work!

**Comment by Pierre-Sassoulas** [comment]
XeLaTeX is a program used to generate latex (like pdflatex), it need to be installed alongside django-survey. Under ubuntu it's `sudo apt-get install texlive-xetex`. I think I did not put it in the documentation properly.

**Comment by gjelsas** [comment]
Itried to install texlive in the python3 container and in alpine linux, but did not get it to work.
I am now using an Ubuntu 18:04 container and it works fine!!
Thanks a lot!

**Comment by Pierre-Sassoulas** [comment]
For the record, this should work on other platforms than ubuntu. The alpine Linux package that you need to install is probably this one: https://pkgs.alpinelinux.org/package/edge/community/x86_64/texlive-xetex. Using a base ubuntu and installing texlive-full will increase the size of your docker image by a lot.
