### ISSUE TITLE
"You can always come back and change them." Is displayed wrongly

### ISSUE THREAD

**Issue by gjelsas** [Pierre-Sassoulas/django-survey#65]
Even if the survey is one write only the success message reads 

> You can always come back and change them.

Hitting the back button or reloading the page doesn't allow reanswering the questions, but the message is always displayed. There should be logic to show this message only if the checkbox "users can alter their answers afterwards" is checked.

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, it was indeed a problem introduced in #50.
