### ISSUE TITLE
More documentation for customization of reports

### ISSUE THREAD

**Issue by gjelsas** [Pierre-Sassoulas/django-survey#67]
Is there somewhere more information about the report function? I would like percentages and the sum of total votes, for example. If you could provide more detailed information about the possibilities of the report function, it would be very welcome!! 

Maybe there is some external documentaion of the used code?

Thanks for your work!

**Comment by Pierre-Sassoulas** [comment]
Hello ! With the CSV export, you can have the raw data as text and treat them with your tool of choice. Using the PDF report, you can have a pie chart, raw text, or a Sankey diagram using only the configuration, see here https://github.com/Pierre-Sassoulas/django-survey#generating-a-pdf-report-from-the-surveys-result. 

But you could also develop and make some other calculations in a custom reporter. You could create your custom class to generate valid tex code with the information you want. See the documentation on custom reporter here: https://github.com/Pierre-Sassoulas/django-survey#implementing-a-custom-treatment. To guide you during development, you could check:
* The default reporter for PieChart: https://github.com/Pierre-Sassoulas/django-survey/blob/master/survey/exporter/tex/question2tex_chart.py#L13
* The Sankey reporter https://github.com/Pierre-Sassoulas/django-survey/blob/master/survey/exporter/tex/question2tex_sankey.py#L15
* The Raw reporter: https://github.com/Pierre-Sassoulas/django-survey/blob/master/survey/exporter/tex/question2tex_raw.py.

Do not hesitate to make a pull request with your new exporter if it can be of interest for others I'll integrate it.

**Comment by Pierre-Sassoulas** [comment]
Maybe you already saw the this documentation ? Is something not clear enough ?

**Comment by gjelsas** [comment]
I just am not skilled enough to understand how to get a report where the count of yes no choices get summed and reported as a total and in percentage. I'll just script some code for parsing the csv-file to output my results!
But thanks for the Answer!
