### ISSUE TITLE
User needs to be able to submit float/real number

### ISSUE THREAD

**Issue by ebdavison** [Pierre-Sassoulas/django-survey#71]
For some instances, a real number (floating point) rather than just an integer is needed.

**Comment by ebdavison** [comment]
OK, so I forked the repo in an attempt to tackle this one.  I found where the data types are but I cannot seem to identify where the code is that renders the UI and field validation.  Can you steer me in the right direction for that bit?

**Comment by Pierre-Sassoulas** [comment]
I think you can check here for the view :https://github.com/Pierre-Sassoulas/django-survey/blob/master/survey/views/survey_detail.py#L31 and here for the template: https://github.com/Pierre-Sassoulas/django-survey/blob/master/survey/templates/survey/question.html. I thought it was "Django bootstrap form" that handle it, but it seems like everything has been redone by hand. (We could remove the dependency if this is not used at all, but I have no time to check that it's really not used).

**Comment by saschalalala** [comment]
@ebdavison I just had a brief look and if I see it correctly, it is enough to specify a new floatfield inside the Question class like this:

```python
# models/question.py
class Question(models.Model):

    TEXT = "text"
    SHORT_TEXT = "short-text"
    RADIO = "radio"
    SELECT = "select"
    SELECT_IMAGE = "select_image"
    SELECT_MULTIPLE = "select-multiple"
    INTEGER = "integer"
    FLOAT = "float" # new 

    QUESTION_TYPES = (
        (TEXT, _("text (multiple line)")),
        (SHORT_TEXT, _("short text (one line)")),
        (RADIO, _("radio")),
        (SELECT, _("select")),
        (SELECT_MULTIPLE, _("Select Multiple")),
        (SELECT_IMAGE, _("Select Image")),
        (INTEGER, _("integer")),
        (FLOAT, _("float")) # new
    )
```

and update the form so that it maps the question type correctly to the respective Django field:

```python
# forms.py
class ResponseForm(models.ModelForm):

     FIELDS = {
        Question.TEXT: forms.CharField,
        Question.SHORT_TEXT: forms.CharField,
        Question.SELECT_MULTIPLE: forms.MultipleChoiceField,
        Question.INTEGER: forms.IntegerField,
        Question.FLOAT: forms.FloatField # new
    }
    # some more code …
    @staticmethod
    def get_question_choices(question):
        """ Return the choices we should use for a question.

        :param Question question: The question
        :rtype: List of String or None """
        qchoices = None
        if question.type not in [Question.TEXT, Question.SHORT_TEXT, Question.INTEGER, Question.FLOAT]: # new element in the list
            qchoices = question.get_choices()
            # add an empty option at the top so that the user has to explicitly
            # select one of the options
            if question.type in [Question.SELECT, Question.SELECT_IMAGE]:
                qchoices = tuple([("", "-------------")]) + qchoices
        return qchoices
```

The rest should be automatically handled by the forms and the template. At least it did, when I did some tests:

![image](https://user-images.githubusercontent.com/3439311/76026877-e814cb80-5f2f-11ea-8e07-5f1dc6b4c19e.png)

Not sure if perhaps I miss a point.
