### ISSUE TITLE
Conditional survey flow

### ISSUE THREAD

**Issue by saschalalala** [Pierre-Sassoulas/django-survey#89]
Is a conditional survey flow something that you would consider inside the scope of this project?

That would mean, you could create flows like:

 - If question A is answered with yes, display question 3, else display question 2, or 
 - If question X is answered with no, skip questions 13 to 28

Longer description e.g. here: https://manual.limesurvey.org/setting_conditions/en

Is something like this already part of the project and if not, would you consider it a useful future enhancement?

It would be quite a big change/feature though and would also require quite a lot of new frontend logic (question show/hide, dynamic link generation for page changes) and adjustments in the backend (e.g. something like a "question skipped because of survey flow" marker/attribute/answer).

I don't have a ready-to-use design in my head or something, just wanted to know your opinion about it.

**Comment by Pierre-Sassoulas** [comment]
The project does not have this, but this is a good feature idea and it was already asked for in #36. As you said there's a lot of thinking to do before implementing it and probably also a lot of actual implementation work :)

**Comment by gannebamm** [comment]
Is there any ambition to implement this? The main idea is quite old.

**Comment by Pierre-Sassoulas** [comment]
Good point, I pinned #36  but it was not in the kanban yet. I'd be glad to accept your merge request  :)
