### ISSUE TITLE
Django LTS 2.2 support

### ISSUE THREAD

**Issue by antnieszka** [Pierre-Sassoulas/django-survey#92]
Hi, is there any reason why current LTS version of Django (2.2) is not supported?
https://github.com/Pierre-Sassoulas/django-survey/commit/8f075c3117fb691ff4b8ab7b6946a89e98044fa5

**Comment by AntonOfTheWoods** [comment]
@antnieszka it is tested (i.e., has a profile in tox.ini) with 2.2 and 3.0 so from that perspective no. @Pierre-Sassoulas may have a reason for requiring that in the `setup.py` though.

**Comment by Pierre-Sassoulas** [comment]
Hello, thank you for opening the issue, there is no good reason to do except that django 3.0 was out and I upgraded. I don't remember if we made incompatible change from django 2.2 to 3.0. If we did not this restriction is probably misguided as django 2.2 seems LTS and will be maintained for "extended support" into 2022 (https://www.djangoproject.com/download/#supported-versions). I don't have time to check compatibility right now, but I would be thankful for a merge request if you tell me it's working with 2.2 and needs this change to use the project easily with pip.

**Comment by AntonOfTheWoods** [comment]
@Pierre-Sassoulas ，I actually did all my testing with 2.2 and was intending sticking with 2.2 until this forced me to upgrade :). As I mentioned, it passes all the tests in tox so it should just be a matter of replacing 3.0 with 2.2 in the `setup.py`

**Comment by Pierre-Sassoulas** [comment]
Ok, sorry for forcing you to upgrade unnecessarily, I'll change that requirement.

**Comment by Pierre-Sassoulas** [comment]
Changes released in `1.3.23` :)

**Comment by antnieszka** [comment]
@Pierre-Sassoulas Thanks! :)
