### ISSUE TITLE
Make pySankeyBeta dependency optional

### ISSUE THREAD

**Issue by quimey** [Pierre-Sassoulas/django-survey#94]
Installing pySankeyBeta brings a lot of heavy dependencies (numpy, scipy, pandas) but I guess those are only needed if you want to create sankey diagrams.

Using the mechanism provided in pep0508, it would be possible to make the dependency optional and to use something like `pip install django-survey-and-report[sankey]` to install it.

What do you think?

**Comment by Pierre-Sassoulas** [comment]
Yes, I've been thinking about that for a long time. I wanted to make two packages originally. One with report the other one with just the survey but I think removing the sankey part makes more sense as the dependencies are really heavy. If there is an easier way than making two packages, I'd be glad to remove those heavy dependencies, thank you for creating the issue.
