### ISSUE TITLE
InterfaceError after submitting the survey

### ISSUE THREAD

**Issue by Asitonie** [Pierre-Sassoulas/django-survey#97]
Hello! Thank you for creating this beautiful app.  I encountered 
**InterfaceError(Error binding parameter 0 - probably unsupported type.) in python3.6/site packages/django/db/backends/sqlite3 /operations.py, line 144, in _quote_params_for_last_executed_quer**
every time I submitted the survey. I'm not sure if is a bug of the package or it is related to my DB setting. Although the error occurs, the submitted form is stored and I can access it through admin.

**Comment by Pierre-Sassoulas** [comment]
It look like a sqlite error. I never encountered it. Did you change the database manually ? I would look at the output of `python manage.py migrate` or maybe dump everything from the database, starting from a new one with syncdb and then loading back with loaddata.

**Comment by neilmillard** [comment]
Seems the UUID is not resolving as a string in the database query.
https://github.com/Pierre-Sassoulas/django-survey/pull/98

**Comment by Asitonie** [comment]
> It look like a sqlite error. I never encountered it. Did you change the database manually ? I would look at the output of `python manage.py migrate` or maybe dump everything from the database, starting from a new one with syncdb and then loading back with loaddata.

No, I did not change the database. In fact, I create a project that only contains this app and only copy and paste the code in the instruction to import it. I try on my own computer and my uni server, both encounter this problem. The output of `python manage.py migrate`  says  "No migrations to apply"

**Comment by Asitonie** [comment]
> Seems the UUID is not resolving as a string in the database query.
> #98

I see. Thank you for answering!

**Comment by Pierre-Sassoulas** [comment]
I'm going to release a new version with @neilmillard  bug fix, in the meantime you can apply it to your local code ;)

**Comment by Asitonie** [comment]
> I'm going to release a new version with @neilmillard bug fix, in the meantime you can apply it to your local code ;)

Thank you so much! :)

**Comment by Pierre-Sassoulas** [comment]
I just released `1.3.24`, sorry for the delay.
